// Generates csp.conf with the sha256 hashes of every inline <script> in the
// build output (the theme script and the JSON-LD blocks), so the CSP can stay
// strict without 'unsafe-inline'. Runs as part of `pnpm build`; the Dockerfile
// copies the result into /etc/nginx/snippets/.
import { createHash } from 'node:crypto'
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const dist = resolve(import.meta.dirname, '..', 'dist')

function htmlFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) =>
    entry.isDirectory()
      ? htmlFiles(join(dir, entry.name))
      : entry.name.endsWith('.html')
        ? [join(dir, entry.name)]
        : [],
  )
}

const files = htmlFiles(dist)
if (files.length === 0) throw new Error('no HTML found in dist/ — run vite build first')

const hashes = new Set()
for (const file of files) {
  const html = readFileSync(file, 'utf8')
  // inline <script> only — anything with a src= attribute is covered by 'self'
  for (const [, body] of html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
    hashes.add(`'sha256-${createHash('sha256').update(body).digest('base64')}'`)
  }
}

const policy = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'self'",
  "form-action 'none'",
  "img-src 'self' data:",
  "font-src 'self'",
  "style-src 'self'",
  "connect-src 'self'",
  `script-src 'self' ${[...hashes].join(' ')}`,
].join('; ')

writeFileSync(
  resolve(dist, '..', 'csp.conf'),
  `# generated by scripts/csp.mjs on every build — do not edit by hand\nadd_header Content-Security-Policy "${policy}" always;\n`,
)

console.log(`csp.conf written — ${hashes.size} inline script hash(es) from ${files.length} page(s)`)
